apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- toYaml .Values.serviceSelectorLabels | nindent 4 }}
