# Default values for the helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# Note about Namespace
# --------------------
# It is deliberately left out here and using the helm -n or --namespace flag you can deploy your resources to the same
# namespace as the release. If you leave it out, your resources will be deployed to the default namespace.
# Also, not that the namespace you are deploying to should already exist otherwise the helm command will fail.
# You can always specify a different namespace for a resource by setting it directly in it's yaml file or
# making it configurable by defining it in this file.

###########
# Deployment and Service
###########
replicaCount: 1
maxUnavailable: 0

chartType: application

image:
  repository: hypertrace/entity-service
  pullPolicy: IfNotPresent
  tagOverride: ""

imagePullSecrets: {}

containerPort: 50061
containerAdminPort: 50062

service:
  name: entity-service
  type: ClusterIP
  port: 50061

nodeLabels: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

securityContext: {}

javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"

livenessProbe:
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 3
startupProbe:
  periodSeconds: 5
  failureThreshold: 24
  timeoutSeconds: 3

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 0.1
    memory: 1024Mi
  limits:
    cpu: 1
    memory: 1024Mi

deploymentLabels:
  app: entity-service

podLabels:
  app: entity-service

podAnnotations: {}

# The Deployment Selector match labels are different from the pod labels. Note that they should be a subset of the pod
# labels. You append new labels to them but cannot remove labels. If you remove or modify the labels you will need to
# delete the existing deployment bearing the same name and then redeploy. This is the reason why they are separated from
# the pod labels. You can add and remove pod labels without having an effect on the deployment.
# Also, please use "apiVersion: apps/v1" instead of the deprecated "apiVersion: extensions/v1beta1" for the deployment
# apiVersion in the yaml file.
deploymentSelectorMatchLabels:
  app: entity-service

serviceSelectorLabels:
  app: entity-service

###########
# Config Maps
###########
entityServiceConfig:
  name: entity-service-config
  publishChangeEvents: false
  postgres:
    host: postgres
    port: 5432
    url: ""
  skipAttributes: []
  changeEnabledEntityTypes: ["*"]
  attributeService:
    host: attribute-service
    port: 9012

database:
  type: mongo
  mongo:
    authEnabled: false
    endpoints:
      - host: mongo-primary-0.mongo-headless
        port: 27017
      - host: mongo-secondary-0.mongo-headless
        port: 27017
    replicaSet: rs0
    authDb: admin
    credentials:
      secretName: mongodb-credentials
      secretUsernameKey: mongodb-service-username
      secretPasswordKey: mongodb-service-password

attributes: []
idAttributes:
  - scope: API
    attribute: API.id
  - scope: SERVICE
    attribute: SERVICE.id
  - scope: BACKEND
    attribute: BACKEND.id
extraAttributes: []

logConfig:
  name: entity-service-log-config
  monitorInterval: 30
  rootLogger:
    level: INFO
  appender:
    rolling:
      enabled: false

config-bootstrapper:
  job:
    prefix: entity
  configurationCommands: {}

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
