name: build and validate
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}

      - name: Build with Gradle
        uses: hypertrace/github-actions/gradle@main
        with:
          args: build dockerBuildImages

      - name: Determine docker tag
        id: tag
        run: echo ::set-output name=tag::$(./gradlew -q printDockerImageDefaultTag | head -1)

      - name: Scan docker image
        uses: azure/container-scan@v0.1
        with:
          image-name: hypertrace/entity-service:${{ steps.tag.outputs.tag }}
        env:
          DOCKLE_HOST: "unix:///var/run/docker.sock"
        continue-on-error: true

  validate-protos:
    runs-on: ubuntu-22.04
    container:
      image: bufbuild/buf:0.56.0
      credentials:
        username: ${{ secrets.DOCKERHUB_READ_USER }}
        password: ${{ secrets.DOCKERHUB_READ_TOKEN }}
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: verify-protos
        run: |
          buf lint
          buf breaking --against "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"


  validate-helm-charts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main
